name: fit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.5.3
  
  rxdart: ^0.27.7

  logging: 1.3.0
  dart_mappable: ^4.6.0
  collection: ^1.19.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  dart_mappable_builder: ^4.6.0

flutter:
  uses-material-design: true
